[terminal]
osc52 = "CopyPaste"

[font]
size = 21.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "F", mods = "Command", action = "None" },
]

[general]
import = [
    "~/.config/omarchy/current/theme/alacritty.toml",
]
