matches:
  - trigger: ":hello"
    replace: "Hello there!"
  - trigger: ":date"
    replace: "{{mydate}}"
  - trigger: ":gm"
    replace: "javier.e.glz@gmail.com"
  - trigger: ":li"
    replace: "https://www.linkedin.com/in/javier123454321/"
  - trigger: ":io"
    replace: "https://javiergonzalez.io"
